name: NicheFlair
favicon: null
layout_spectrum: 0.010048016207292676
typography_spectrum: 0.5650449118111283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8500610217452049
  lightness: 0.15553817129693925
  saturation: 0.2885510688647628
  rhythmicContrast: 0.6024268548935652
purpose: []
